<a href="https://colab.research.google.com/github/ValeriaGubanova/ml/blob/main/06_hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
print(np.__version__)

1.21.6


2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.linspace(7, 7, 7)

array([7., 7., 7., 7., 7., 7., 7.])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
np.flip(np.random.randn(5))

array([ 0.87427585, -1.63204675, -2.22024652,  0.24001223, -0.4471709 ])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(0, 9, 1).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
array = np.diag(np.arange(1, 5), k=0)
array[array == 0 ] = 7
print(array)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
np.tile(np.arange(0,5,1),5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
X = np.random.random((10,10))
Y = X - X.mean()
print(Y)

[[ 0.05028039 -0.3464129  -0.48278162  0.40159857 -0.04921214  0.18311207
  -0.48328738  0.27622799  0.37833194 -0.38363646]
 [ 0.10629285 -0.21453782 -0.23889827 -0.23696748  0.05562908  0.23432346
  -0.10984611  0.18910045  0.36389583 -0.14855621]
 [-0.32209441 -0.51172927 -0.26135819  0.23027217  0.18727853  0.38030575
   0.28246349 -0.49494604  0.32406406 -0.22717269]
 [ 0.32121856 -0.12273541 -0.08090038  0.26715378 -0.06622481  0.3719512
  -0.4720566  -0.46235823  0.44058042 -0.23735181]
 [-0.33591536 -0.21207187 -0.43191232  0.28456206 -0.03895505  0.1259812
   0.00638345  0.0824388  -0.32658983 -0.46555776]
 [ 0.23968858 -0.02483281  0.13081291 -0.50316085  0.17758404 -0.41865234
   0.32648259 -0.03016549 -0.15161418 -0.20449116]
 [ 0.34861603  0.27136269  0.39607541 -0.01506811  0.06762675  0.44698084
  -0.08039331  0.34320724 -0.18253287 -0.18030413]
 [ 0.25093375 -0.35888077  0.08313663  0.43477138 -0.08636452  0.46421555
  -0.21064457 -0.01876993  0.44501095  0.22041096]
 [

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [3]:
arr = np.random.randint(9, size = (10,10))
arr - np.median(arr)

array([[-4., -2., -4.,  0.,  0., -1.,  4.,  2.,  4.,  3.],
       [-1.,  0.,  0., -2., -3.,  3., -4.,  4., -4., -1.],
       [-3., -3.,  3., -2., -2., -2.,  4.,  1., -1.,  1.],
       [ 0.,  4.,  3., -3.,  4., -2., -4.,  4., -3.,  1.],
       [-1., -3., -2., -3.,  1.,  0., -4.,  2., -2., -2.],
       [-2.,  1., -4., -4.,  4., -4.,  0.,  0., -2., -2.],
       [ 1., -4.,  4., -3.,  0., -2.,  0., -4., -4.,  3.],
       [ 4.,  2.,  2.,  3.,  4.,  1.,  1.,  3., -2.,  0.],
       [ 4., -3., -4., -1., -3.,  2.,  1.,  0.,  0.,  3.],
       [ 4.,  2., -4., -2., -1., -2.,  3.,  1.,  3.,  0.]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
arr = np.random.randint(9, size = (5,5))
max = np.amax(arr, axis = 1, keepdims = True)
min = np.amin(arr, axis = 1, keepdims = True)
np.concatenate((arr, max, min), axis = 1)

array([[7, 7, 0, 3, 5, 7, 0],
       [5, 6, 2, 1, 2, 6, 1],
       [7, 2, 5, 0, 8, 8, 0],
       [7, 2, 3, 2, 8, 8, 2],
       [3, 5, 5, 3, 3, 5, 3]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
arr = np.arange(1, 51)
odds = arr[::2].reshape(5,5)
arr = np.arange(2,51)
evens = arr[::2].reshape(5,5)
mul = np.matmul(odds, evens)
print(mul)

[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [ ]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
